# Ejercicio Vinos
## Emilio León y Sofía Blancas
### 09/03/2026

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [4]:
df_vinos = pd.read_csv("wines-1-1.csv")
df_vinos.head()

,Year,Price,WinterRain,AGST,HarvestRain,Age,FrancePop
0,1952,7.4950,600,17.1167,160,31,43183.569
1,1953,8.0393,690,16.7333,80,30,43495.030
2,1955,7.6858,502,17.1500,130,28,44217.857
3,1957,6.9845,420,16.1333,110,26,45152.252
4,1958,6.7772,582,16.4167,187,25,45653.805


In [20]:
df_vinos["Price"].max()

8.4937

In [21]:
df_vinos["Price"].min()

6.2049

#### El precio esta entre 8.5 y 6.2 redondeando, tal vez normalizando podríamos ver la predicción de la calidad

In [5]:
df_vinos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Year         27 non-null     int64  
 1   Price        27 non-null     float64
 2   WinterRain   27 non-null     int64  
 3   AGST         27 non-null     float64
 4   HarvestRain  27 non-null     int64  
 5   Age          27 non-null     int64  
 6   FrancePop    27 non-null     float64
dtypes: float64(3), int64(4)
memory usage: 1.6 KB


#### Podemos predecir la calidad del vino? según su precio?
#### Nuestra y será el precio.
#### Nuestras x serán WinterRain, AGST, HarvestRain, y Age
#### Son las más determinantes debido a que son las que más información nos dan sobre la calidad del vino.

In [8]:
df_vinos[["WinterRain", "AGST", "HarvestRain", "Age"]].corr()

,WinterRain,AGST,HarvestRain,Age
WinterRain,1.000000,-0.321132,-0.267989,-0.051184
AGST,-0.321132,1.000000,-0.027084,0.294883
HarvestRain,-0.267989,-0.027084,1.000000,0.058850
Age,-0.051184,0.294883,0.058850,1.000000


#### Ninguna de nuestras variables tienen una correlación alta como para excluirlas.

In [9]:
X = df_vinos[["WinterRain", "AGST", "HarvestRain", "Age"]]
y = df_vinos["Price"]

In [10]:
lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [12]:
a0 = lr.intercept_
a1 = lr.coef_[0]
a2 = lr.coef_[1]
a3 = lr.coef_[2]
a4 = lr.coef_[3]
print("La ecuación es: y =", a0,"+ ", a1,"x1 + ", a2,"x2 + ", a3,"x3 + ", a4,"x4")

La ecuación es: y = -3.6515703302352254 +  0.001166719144632399 x1 +  0.6163915583348174 x2 +  -0.0038605996477244935 x3 +  0.02384801420540343 x4


In [15]:
R2 = lr.score(X, y)
R2

0.8275317042479997

#### La regresión es bastante buena.

In [16]:
dic = {'WinterRain': [600], 'AGST': [15], 'HarvestRain': [150], 'Age': [15]}
df_predic = pd.DataFrame(dic)
df_predic

,WinterRain,AGST,HarvestRain,Age
0,600,15,150,15


In [17]:
price_predic = lr.predict(df_predic)
price_predic

array([6.0729648])

In [18]:
df_predic['Price'] = price_predic
df_predic

,WinterRain,AGST,HarvestRain,Age,Price
0,600,15,150,15,6.072965


In [22]:
scaler = StandardScaler()

In [23]:
df_norm = pd.DataFrame(scaler.fit_transform(df_vinos), columns=df_vinos.columns)

In [24]:
df_norm

,Year,Price,WinterRain,AGST,HarvestRain,Age,FrancePop
0,-1.830745,0.727528,-0.066397,0.987712,0.211788,1.830745,-1.854298
1,-1.707170,1.601587,0.644375,0.395009,-0.903972,1.707170,-1.770619
2,-1.460019,1.033922,-0.840349,1.039191,-0.206622,1.460019,-1.576420
3,-1.212869,-0.092252,-1.487941,-0.532538,-0.485562,1.212869,-1.325380
4,-1.089293,-0.425143,-0.208552,-0.094427,0.588357,1.089293,-1.190630
5,-0.965718,1.660039,-0.974606,1.554444,0.588357,0.965718,-1.063059
6,-0.842143,-0.840092,1.220890,-0.094427,2.024898,0.842143,-0.940720
7,-0.718567,2.331280,1.750020,1.322557,-1.489746,0.718567,-0.794563
8,-0.594992,0.555704,0.699657,-0.274835,-1.294488,0.594992,-0.536464
9,-0.471417,-0.528720,-0.003217,-1.176565,0.142053,0.471417,-0.345626


In [43]:
df_norm["Price"].max()

2.3312797660142635

In [29]:
X1 = df_norm[["WinterRain", "AGST", "HarvestRain", "Age"]]
y1 = df_norm["Price"]

In [30]:
lr1 = LinearRegression()
lr1.fit(X1, y1)

LinearRegression()

In [31]:
a0_rec1 = lr1.intercept_
a1_rec1 = lr1.coef_[0]
a2_rec1 = lr1.coef_[1]
a3_rec1 = lr1.coef_[2]
a4_rec1 = lr1.coef_[3]
print("La ecuación es: y =", a0_rec1,"+ ", a1_rec1,"x1 + ", a2_rec1,"x2 + ", a3_rec1,"x3 + ", a4_rec1,"x4")

La ecuación es: y = 2.1920699222016786e-15 +  0.2372359497033427 x1 +  0.6402856187714447 x2 +  -0.44450433109620885 x3 +  0.3099007114312625 x4


#### Podemos ver que la ecuación cambia

In [39]:
dic = {'WinterRain': [600], 'AGST': [15], 'HarvestRain': [150], 'Age': [15]}
df_predic1 = pd.DataFrame(dic)
df_predic1

,WinterRain,AGST,HarvestRain,Age
0,600,15,150,15


In [40]:
price_predic_rec1 = lr1.predict(df_predic1)
price_predic_rec1

array([89.91871511])

#### No tiene sentido porque los valores no están normalizados.Podríamos normalizarlo.

In [41]:
df_predic1 = pd.DataFrame(scaler.fit_transform(df_predic1), columns=df_predic1.columns)
df_predic1

,WinterRain,AGST,HarvestRain,Age
0,0.0,0.0,0.0,0.0


#### Todo se hizo 0, porque no tiene más valores con los cuál normalizar.

In [42]:
price_predic_rec1_2 = lr1.predict(df_predic1)
price_predic_rec1_2

array([2.19206992e-15])

#### Creo que este valor tiene un poco más de sentido que el otro, pero aún no me convence.
#### Por lo que en este caso no veo una ventaja de trabajar con los valores normalizados, tal vez si usaramos otro tipo
#### De normalización, se podría.